//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_WebNovel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackBook
    {
        public int blackId { get; set; }
        public Nullable<int> bookId { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
