//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_WebNovel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int comment_id { get; set; }
        public Nullable<int> chapter_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string comment_text { get; set; }
        public Nullable<System.DateTime> comment_created_at { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        public virtual User User { get; set; }
    }
}
